//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEROLINEA
    {
        public string ID_AEROLINEA { get; set; }
        public string NOMBRE_AEROLINEA { get; set; }
        public Nullable<int> ID_IMAGEN_AEROLINEAFK { get; set; }
    }
}
