//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int ID_BITACORA { get; set; }
        public string USUARIO_BITACORA { get; set; }
        public string FECHA_BITACORA { get; set; }
        public string CODIGO_BITACORA { get; set; }
        public string TIPO_BITACORA { get; set; }
        public string DESCRIPCION_BITACORA { get; set; }
        public string DETALLE_BITACORA { get; set; }
    }
}
