//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public int ID_BITACORA { get; set; }
        public string USUARIO_BITACORA { get; set; }
        public string FECHA_BITACORA { get; set; }
        public string CODIGO_BITACORA { get; set; }
        public string TIPO_BITACORA { get; set; }
        public string DESCRIPCION_BITACORA { get; set; }
        public string DETALLE_BITACORA { get; set; }
    }
}
