//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ID_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string PRIMER_APELLIDO_CLIENTE { get; set; }
        public string SEGUNDO_APELLIDO_CLIENTE { get; set; }
        public string EMAIL_CLIENTE { get; set; }
        public string USERNAME_CLIENTE { get; set; }
        public string CLAVE_CLIENTE { get; set; }
    }
}
