//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAR_BOLETO
    {
        public int ID_BOLETO { get; set; }
        public Nullable<int> ID_USUARIOFK { get; set; }
        public string FECHA_COMPRAR_BOLETO { get; set; }
        public string PAGO_COMPRAR_BOLETO { get; set; }
        public Nullable<int> MONTO_COMPRAR_BOLETO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
