//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRAR_BOLETO
    {
        public int ID_BOLETO { get; set; }
        public Nullable<int> ID_USUARIOFK { get; set; }
        public string FECHA_COMPRAR_BOLETO { get; set; }
        public string PAGO_COMPRAR_BOLETO { get; set; }
        public Nullable<int> MONTO_COMPRAR_BOLETO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
