//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSECUTIVO_AEROLINEA
    {
        public int ID_CONSECUTIVO_AEROLINEA { get; set; }
        public string CONSECUTIVO_AEROLINEA1 { get; set; }
        public string PREFIJO_AEROLINEA { get; set; }
        public Nullable<int> RANGO_INICIAL_AEROLINEA { get; set; }
        public Nullable<int> RANGO_FINAL_AEROLINEA { get; set; }
    }
}
