//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSECUTIVO_PUERTA
    {
        public int ID_CONSECUTIVO_PUERTA { get; set; }
        public string CONSECUTIVO_PUERTA1 { get; set; }
        public string PREFIJO_PUERTA { get; set; }
        public Nullable<int> RANGO_INICIAL_PUERTA { get; set; }
        public Nullable<int> RANGO_FINAL_PUERTA { get; set; }
    }
}
