//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSECUTIVO_VUELO
    {
        public int ID_CONSECUTIVO_VUELO { get; set; }
        public string CONSECUTIVO_VUELO1 { get; set; }
        public string PREFIJO_VUELO { get; set; }
        public Nullable<int> RANGO_INICIAL_VUELO { get; set; }
        public Nullable<int> RANGO_FINAL_VUELO { get; set; }
    }
}
