//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class servicioswebEntities : DbContext
    {
        public servicioswebEntities()
            : base("name=servicioswebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AEROLINEA> AEROLINEA { get; set; }
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMPRAR_BOLETO> COMPRAR_BOLETO { get; set; }
        public virtual DbSet<CONSECUTIVO_AEROLINEA> CONSECUTIVO_AEROLINEA { get; set; }
        public virtual DbSet<CONSECUTIVO_PAIS> CONSECUTIVO_PAIS { get; set; }
        public virtual DbSet<CONSECUTIVO_PUERTA> CONSECUTIVO_PUERTA { get; set; }
        public virtual DbSet<CONSECUTIVO_VUELO> CONSECUTIVO_VUELO { get; set; }
        public virtual DbSet<ERROR> ERROR { get; set; }
        public virtual DbSet<IMAGEN_AEROLINEA> IMAGEN_AEROLINEA { get; set; }
        public virtual DbSet<IMAGEN_PAIS> IMAGEN_PAIS { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PUERTA> PUERTA { get; set; }
        public virtual DbSet<RESERVAR_BOLETO> RESERVAR_BOLETO { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TARJETA> TARJETA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VUELO_LLEGADA> VUELO_LLEGADA { get; set; }
        public virtual DbSet<VUELO_SALIDA> VUELO_SALIDA { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
