//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public string ID_PAIS { get; set; }
        public string NOMBRE_PAIS { get; set; }
        public Nullable<int> ID_IMAGEN_PAISFK { get; set; }
    
        public virtual IMAGEN_PAIS IMAGEN_PAIS { get; set; }
    }
}
