//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUERTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUERTA()
        {
            this.VUELO_LLEGADA = new HashSet<VUELO_LLEGADA>();
            this.VUELO_SALIDA = new HashSet<VUELO_SALIDA>();
        }
    
        public string ID_PUERTA { get; set; }
        public Nullable<int> NUMERO_PUERTA { get; set; }
        public string DETALLE_PUERTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUELO_LLEGADA> VUELO_LLEGADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VUELO_SALIDA> VUELO_SALIDA { get; set; }
    }
}
