//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAR_BOLETO
    {
        public int ID_RESERVAR_BOLETO { get; set; }
        public string BOOKING_ID { get; set; }
        public string CANTIDAD_RESERVAR_BOLETOS { get; set; }
        public string TOTAL_RESERVAR_BOLETO { get; set; }
        public Nullable<int> ID_CLIENTEFK { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
