//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        public int ID_TARJETA { get; set; }
        public Nullable<int> MES_TARJETA { get; set; }
        public Nullable<int> YEAR_TARJETA { get; set; }
        public Nullable<int> CVV_TARJETA { get; set; }
        public string TIPO_TARJETA { get; set; }
        public Nullable<int> ID_USUARIOFK { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
