//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        public int ID_TARJETA { get; set; }
        public Nullable<int> MES_TARJETA { get; set; }
        public Nullable<int> YEAR_TARJETA { get; set; }
        public Nullable<int> CVV_TARJETA { get; set; }
        public string TIPO_TARJETA { get; set; }
        public Nullable<int> ID_CLIENTEFK { get; set; }
    }
}
