//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CLAVE_USUARIO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string PREGUNTA_SEGURIDAD_USUARIO { get; set; }
        public string RESPUESTA_SEGURIDAD_USUARIO { get; set; }
        public Nullable<int> ID_ROLFK { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
