//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.COMPRAR_BOLETO = new HashSet<COMPRAR_BOLETO>();
            this.RESERVAR_BOLETO = new HashSet<RESERVAR_BOLETO>();
            this.TARJETA = new HashSet<TARJETA>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CLAVE_USUARIO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string PREGUNTA_SEGURIDAD_USUARIO { get; set; }
        public string RESPUESTA_SEGURIDAD_USUARIO { get; set; }
        public Nullable<int> ID_ROLFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRAR_BOLETO> COMPRAR_BOLETO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVAR_BOLETO> RESERVAR_BOLETO { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARJETA> TARJETA { get; set; }
    }
}
