//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CLAVE_USUARIO { get; set; }
        public string EMAIL_USUARIO { get; set; }
        public string PREGUNTA_SEGURIDAD_USUARIO { get; set; }
        public string RESPUESTA_SEGURIDAD_USUARIO { get; set; }
        public Nullable<int> ID_ROLFK { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
