//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUELO_LLEGADA
    {
        public string ID_VUELO_LLEGADA { get; set; }
        public string ID_AEROLINEAFK { get; set; }
        public string PROCEDENCIA_VUELO_LLEGADA { get; set; }
        public string FECHA_VUELO_LLEGADA { get; set; }
        public string HORA_VUELO_LLEGADA { get; set; }
        public string ID_PUERTAFK { get; set; }
    }
}
