//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V_VuelosServiciosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUELO_LLEGADA
    {
        public string ID_VUELO_LLEGADA { get; set; }
        public string ID_AEROLINEAFK { get; set; }
        public string PROCEDENCIA_VUELO_LLEGADA { get; set; }
        public string FECHA_VUELO_LLEGADA { get; set; }
        public string HORA_VUELO_LLEGADA { get; set; }
        public string ID_PUERTAFK { get; set; }
    
        public virtual AEROLINEA AEROLINEA { get; set; }
        public virtual PUERTA PUERTA { get; set; }
    }
}
